version: "3.3"

services:
  keycloak.local:
    image: quay.io/keycloak/keycloak:16.1.0
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VERSION: h2
      KEYCLOAK_FRONTEND_URL: http://0.0.0.0:8080/auth
    networks:
      - docker-compose-network

networks:
  docker-compose-network:
    ipam:
      config:
        - subnet: 172.24.24.0/24
